name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      # Install dependencies
      - run: npm ci

      # Build React app
      - run: CI=false npm run build

      # Install Firebase CLI
      - run: npm install -g firebase-tools

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_STELLABROS_D9A7C }}
          channelId: live
          projectId: stellabros-d9a7c
